version: 2.1

# Custom executors definition
executors:
  node:
    docker:
      - image: circleci/node:12

jobs:
  build:
    executor:
      name: node
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm --version
            - run: node --version
  test-and-coverage:
    executor:
      name: node
    steps:
      - run: npm run coverage
  code-conformance:
    executor:
      name: node
    steps:
      - run: npm run validate
workflows:
    build-and-test:
      jobs:
        - build
        - test-and-coverage:
            requires:
              - build
        - code-conformance:
            requires:
              - build