version: 2.1
orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm --version
            - run: node --version
  test-and-coverage:
    executor:
      name: node/default
    steps:
      - run: npm run coverage
  code-conformance:
    executor:
      name: node/default
    steps:
      - run: npm run validate
workflows:
    build-and-test:
      jobs:
        - build
        - test-and-coverage:
            requires:
              - build
        - code-conformance:
            requires:
              - build